name: VanillaPaper
main: net.evmodder.vanillapaper.VanillaPaper
author: EvModder
website: https://github.com/EvModder/VanillaPaper
description: Attempts to fix certain vanilla mechanics on Paper.
version: 1.0
api-version: 1.13